// Generated by CoffeeScript 1.8.0
(function() {
  var ppp;

  ppp = require("parse-ply");

  ppp(process.stdin, function(err, ply) {
    if (err) {
      console.log(err);
      return;
    }
    console.log(ply);
  });

}).call(this);
